[package]
name = "my_bpe_tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
fancy-regex = "0.13.0"
lazy_static = "1.5.0"
phf = { version = "0.11", features = ["macros"] }
regex = "1.11.0"
